<?php

namespace Rudak\OwnLoggerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{
    public function getLogs($nb = 50)
    {
        $qb = $this->createQueryBuilder('l')
            ->setMaxResults($nb)
            ->orderBy('l.id', 'DESC')
            ->getQuery();
        return $qb->execute();
    }
}
